<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ChartOfAccount;
use App\Models\Company;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class ChartOfAccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Creates a standard Chart of Accounts for each company
     */
    public function run(): void
    {
        // Get all companies or create a default one
        $companies = Company::all();
        
        if ($companies->isEmpty()) {
            $this->command->info('No companies found. Please create a company first.');
            return;
        }

        foreach ($companies as $company) {
            $this->command->info("Creating Chart of Accounts for: {$company->name}");
            $this->createChartOfAccounts($company->id);
        }
    }

    /**
     * Create standard Chart of Accounts for a company
     */
    public function createChartOfAccounts(string $companyId): void
    {
        // Check if accounts already exist for this company
        $existingCount = ChartOfAccount::where('company_id', $companyId)->count();
        if ($existingCount > 0) {
            $this->command->warn("  → Skipping: {$existingCount} accounts already exist for this company.");
            return;
        }

        $accounts = $this->getStandardChartOfAccounts();
        
        DB::beginTransaction();
        try {
            $parentIds = [];
            
            foreach ($accounts as $account) {
                $parentId = null;
                
                // If this account has a parent, look it up
                if (!empty($account['parent_code'])) {
                    $parentId = $parentIds[$account['parent_code']] ?? null;
                }

                $newAccount = ChartOfAccount::create([
                    'id' => (string) Str::uuid(),
                    'company_id' => $companyId,
                    'account_code' => $account['code'],
                    'account_name' => $account['name'],
                    'account_type' => $account['type'],
                    'account_subtype' => $account['subtype'],
                    'parent_id' => $parentId,
                    'description' => $account['description'] ?? null,
                    'is_active' => true,
                    'is_system_account' => $account['is_system'] ?? false,
                    'opening_balance' => 0,
                    'normal_balance' => $account['normal_balance'],
                    'tax_code' => $account['tax_code'] ?? null,
                ]);

                // Store the ID for potential child accounts
                $parentIds[$account['code']] = $newAccount->id;
            }

            DB::commit();
            $this->command->info("  ✓ Created " . count($accounts) . " accounts successfully.");
            
        } catch (\Exception $e) {
            DB::rollBack();
            $this->command->error("  ✗ Error: " . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Returns the standard Chart of Accounts structure
     */
    private function getStandardChartOfAccounts(): array
    {
        return [
            // =====================================================
            // ASSETS (1000-1999)
            // =====================================================
            
            // Current Assets (1000-1499)
            [
                'code' => '1000',
                'name' => 'Current Assets',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'normal_balance' => 'debit',
                'description' => 'Assets expected to be converted to cash within one year',
                'is_system' => true,
            ],
            [
                'code' => '1010',
                'name' => 'Cash on Hand',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1000',
                'normal_balance' => 'debit',
                'description' => 'Physical cash held at business locations',
            ],
            [
                'code' => '1020',
                'name' => 'Petty Cash',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1000',
                'normal_balance' => 'debit',
                'description' => 'Small cash fund for minor expenses',
            ],
            [
                'code' => '1100',
                'name' => 'Cash in Bank',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1000',
                'normal_balance' => 'debit',
                'description' => 'Cash held in bank accounts',
                'is_system' => true,
            ],
            [
                'code' => '1110',
                'name' => 'Main Operating Account',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1100',
                'normal_balance' => 'debit',
                'description' => 'Primary business bank account',
            ],
            [
                'code' => '1120',
                'name' => 'Payroll Account',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1100',
                'normal_balance' => 'debit',
                'description' => 'Bank account for payroll transactions',
            ],
            [
                'code' => '1130',
                'name' => 'M-Pesa Float',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1100',
                'normal_balance' => 'debit',
                'description' => 'Mobile money float balance',
            ],
            [
                'code' => '1200',
                'name' => 'Accounts Receivable',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1000',
                'normal_balance' => 'debit',
                'description' => 'Amounts owed by customers',
                'is_system' => true,
            ],
            [
                'code' => '1210',
                'name' => 'Trade Receivables',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1200',
                'normal_balance' => 'debit',
                'description' => 'Receivables from normal business operations',
            ],
            [
                'code' => '1220',
                'name' => 'Allowance for Doubtful Accounts',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1200',
                'normal_balance' => 'credit',
                'description' => 'Estimated uncollectible receivables (contra account)',
            ],
            [
                'code' => '1300',
                'name' => 'Inventory',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1000',
                'normal_balance' => 'debit',
                'description' => 'Goods held for sale',
                'is_system' => true,
            ],
            [
                'code' => '1310',
                'name' => 'Finished Goods Inventory',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1300',
                'normal_balance' => 'debit',
                'description' => 'Completed products ready for sale',
            ],
            [
                'code' => '1320',
                'name' => 'Raw Materials Inventory',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1300',
                'normal_balance' => 'debit',
                'description' => 'Materials to be used in production',
            ],
            [
                'code' => '1330',
                'name' => 'Work in Progress',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1300',
                'normal_balance' => 'debit',
                'description' => 'Partially completed products',
            ],
            [
                'code' => '1400',
                'name' => 'Prepaid Expenses',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1000',
                'normal_balance' => 'debit',
                'description' => 'Expenses paid in advance',
            ],
            [
                'code' => '1410',
                'name' => 'Prepaid Rent',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1400',
                'normal_balance' => 'debit',
                'description' => 'Rent paid in advance',
            ],
            [
                'code' => '1420',
                'name' => 'Prepaid Insurance',
                'type' => 'asset',
                'subtype' => 'current_asset',
                'parent_code' => '1400',
                'normal_balance' => 'debit',
                'description' => 'Insurance premiums paid in advance',
            ],
            
            // Fixed Assets (1500-1799)
            [
                'code' => '1500',
                'name' => 'Fixed Assets',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'normal_balance' => 'debit',
                'description' => 'Long-term tangible assets',
                'is_system' => true,
            ],
            [
                'code' => '1510',
                'name' => 'Land',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1500',
                'normal_balance' => 'debit',
                'description' => 'Land owned by the business',
            ],
            [
                'code' => '1520',
                'name' => 'Buildings',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1500',
                'normal_balance' => 'debit',
                'description' => 'Buildings owned by the business',
            ],
            [
                'code' => '1521',
                'name' => 'Accumulated Depreciation - Buildings',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1520',
                'normal_balance' => 'credit',
                'description' => 'Total depreciation on buildings (contra account)',
            ],
            [
                'code' => '1530',
                'name' => 'Vehicles',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1500',
                'normal_balance' => 'debit',
                'description' => 'Motor vehicles owned by the business',
            ],
            [
                'code' => '1531',
                'name' => 'Accumulated Depreciation - Vehicles',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1530',
                'normal_balance' => 'credit',
                'description' => 'Total depreciation on vehicles (contra account)',
            ],
            [
                'code' => '1540',
                'name' => 'Furniture & Fixtures',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1500',
                'normal_balance' => 'debit',
                'description' => 'Office furniture and fixtures',
            ],
            [
                'code' => '1541',
                'name' => 'Accumulated Depreciation - Furniture',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1540',
                'normal_balance' => 'credit',
                'description' => 'Total depreciation on furniture (contra account)',
            ],
            [
                'code' => '1550',
                'name' => 'Equipment',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1500',
                'normal_balance' => 'debit',
                'description' => 'Business equipment and machinery',
            ],
            [
                'code' => '1551',
                'name' => 'Accumulated Depreciation - Equipment',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1550',
                'normal_balance' => 'credit',
                'description' => 'Total depreciation on equipment (contra account)',
            ],
            [
                'code' => '1560',
                'name' => 'Computer Equipment',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1500',
                'normal_balance' => 'debit',
                'description' => 'Computers and IT equipment',
            ],
            [
                'code' => '1561',
                'name' => 'Accumulated Depreciation - Computers',
                'type' => 'asset',
                'subtype' => 'fixed_asset',
                'parent_code' => '1560',
                'normal_balance' => 'credit',
                'description' => 'Total depreciation on computers (contra account)',
            ],

            // Other Assets (1800-1999)
            [
                'code' => '1800',
                'name' => 'Other Assets',
                'type' => 'asset',
                'subtype' => 'other_asset',
                'normal_balance' => 'debit',
                'description' => 'Miscellaneous assets',
            ],
            [
                'code' => '1810',
                'name' => 'Security Deposits',
                'type' => 'asset',
                'subtype' => 'other_asset',
                'parent_code' => '1800',
                'normal_balance' => 'debit',
                'description' => 'Deposits held by others (e.g., rent deposits)',
            ],
            [
                'code' => '1820',
                'name' => 'Intangible Assets',
                'type' => 'asset',
                'subtype' => 'other_asset',
                'parent_code' => '1800',
                'normal_balance' => 'debit',
                'description' => 'Non-physical assets like patents, trademarks',
            ],

            // =====================================================
            // LIABILITIES (2000-2999)
            // =====================================================
            
            // Current Liabilities (2000-2499)
            [
                'code' => '2000',
                'name' => 'Current Liabilities',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'normal_balance' => 'credit',
                'description' => 'Obligations due within one year',
                'is_system' => true,
            ],
            [
                'code' => '2100',
                'name' => 'Accounts Payable',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2000',
                'normal_balance' => 'credit',
                'description' => 'Amounts owed to suppliers',
                'is_system' => true,
            ],
            [
                'code' => '2110',
                'name' => 'Trade Payables',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2100',
                'normal_balance' => 'credit',
                'description' => 'Payables from normal business operations',
            ],
            [
                'code' => '2200',
                'name' => 'Accrued Expenses',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2000',
                'normal_balance' => 'credit',
                'description' => 'Expenses incurred but not yet paid',
            ],
            [
                'code' => '2210',
                'name' => 'Accrued Salaries',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2200',
                'normal_balance' => 'credit',
                'description' => 'Salaries earned but not yet paid',
            ],
            [
                'code' => '2220',
                'name' => 'Accrued Utilities',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2200',
                'normal_balance' => 'credit',
                'description' => 'Utility expenses incurred but not yet paid',
            ],
            [
                'code' => '2300',
                'name' => 'Taxes Payable',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2000',
                'normal_balance' => 'credit',
                'description' => 'Tax obligations',
                'is_system' => true,
            ],
            [
                'code' => '2310',
                'name' => 'VAT Payable',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2300',
                'normal_balance' => 'credit',
                'description' => 'Value Added Tax collected from sales',
                'tax_code' => 'VAT',
            ],
            [
                'code' => '2320',
                'name' => 'PAYE Payable',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2300',
                'normal_balance' => 'credit',
                'description' => 'Pay As You Earn tax withheld from employees',
                'tax_code' => 'PAYE',
            ],
            [
                'code' => '2330',
                'name' => 'NSSF Payable',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2300',
                'normal_balance' => 'credit',
                'description' => 'National Social Security Fund contributions',
            ],
            [
                'code' => '2340',
                'name' => 'NHIF Payable',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2300',
                'normal_balance' => 'credit',
                'description' => 'National Hospital Insurance Fund contributions',
            ],
            [
                'code' => '2350',
                'name' => 'Withholding Tax Payable',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2300',
                'normal_balance' => 'credit',
                'description' => 'Withholding tax on payments',
                'tax_code' => 'WHT',
            ],
            [
                'code' => '2360',
                'name' => 'Corporate Tax Payable',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2300',
                'normal_balance' => 'credit',
                'description' => 'Corporate income tax payable',
            ],
            [
                'code' => '2400',
                'name' => 'Short-term Loans',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2000',
                'normal_balance' => 'credit',
                'description' => 'Loans due within one year',
            ],
            [
                'code' => '2410',
                'name' => 'Bank Overdraft',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2400',
                'normal_balance' => 'credit',
                'description' => 'Overdraft facility balance',
            ],
            [
                'code' => '2450',
                'name' => 'Unearned Revenue',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2000',
                'normal_balance' => 'credit',
                'description' => 'Payments received before service delivery',
            ],
            [
                'code' => '2460',
                'name' => 'Customer Deposits',
                'type' => 'liability',
                'subtype' => 'current_liability',
                'parent_code' => '2000',
                'normal_balance' => 'credit',
                'description' => 'Deposits received from customers',
            ],

            // Long-term Liabilities (2500-2999)
            [
                'code' => '2500',
                'name' => 'Long-term Liabilities',
                'type' => 'liability',
                'subtype' => 'long_term_liability',
                'normal_balance' => 'credit',
                'description' => 'Obligations due after one year',
                'is_system' => true,
            ],
            [
                'code' => '2510',
                'name' => 'Bank Loans',
                'type' => 'liability',
                'subtype' => 'long_term_liability',
                'parent_code' => '2500',
                'normal_balance' => 'credit',
                'description' => 'Long-term bank loans',
            ],
            [
                'code' => '2520',
                'name' => 'Asset Finance',
                'type' => 'liability',
                'subtype' => 'long_term_liability',
                'parent_code' => '2500',
                'normal_balance' => 'credit',
                'description' => 'Finance for asset purchases',
            ],
            [
                'code' => '2530',
                'name' => 'Shareholder Loans',
                'type' => 'liability',
                'subtype' => 'long_term_liability',
                'parent_code' => '2500',
                'normal_balance' => 'credit',
                'description' => 'Loans from shareholders/directors',
            ],

            // =====================================================
            // EQUITY (3000-3999)
            // =====================================================
            [
                'code' => '3000',
                'name' => 'Equity',
                'type' => 'equity',
                'subtype' => 'owner_equity',
                'normal_balance' => 'credit',
                'description' => 'Owner\'s equity in the business',
                'is_system' => true,
            ],
            [
                'code' => '3100',
                'name' => 'Share Capital',
                'type' => 'equity',
                'subtype' => 'owner_equity',
                'parent_code' => '3000',
                'normal_balance' => 'credit',
                'description' => 'Capital contributed by shareholders',
            ],
            [
                'code' => '3110',
                'name' => 'Ordinary Share Capital',
                'type' => 'equity',
                'subtype' => 'owner_equity',
                'parent_code' => '3100',
                'normal_balance' => 'credit',
                'description' => 'Common stock issued',
            ],
            [
                'code' => '3120',
                'name' => 'Share Premium',
                'type' => 'equity',
                'subtype' => 'owner_equity',
                'parent_code' => '3100',
                'normal_balance' => 'credit',
                'description' => 'Amount received above par value',
            ],
            [
                'code' => '3200',
                'name' => 'Retained Earnings',
                'type' => 'equity',
                'subtype' => 'retained_earnings',
                'parent_code' => '3000',
                'normal_balance' => 'credit',
                'description' => 'Accumulated profits not distributed',
                'is_system' => true,
            ],
            [
                'code' => '3210',
                'name' => 'Prior Year Retained Earnings',
                'type' => 'equity',
                'subtype' => 'retained_earnings',
                'parent_code' => '3200',
                'normal_balance' => 'credit',
                'description' => 'Retained earnings from previous years',
            ],
            [
                'code' => '3220',
                'name' => 'Current Year Earnings',
                'type' => 'equity',
                'subtype' => 'retained_earnings',
                'parent_code' => '3200',
                'normal_balance' => 'credit',
                'description' => 'Net income for current year (system calculated)',
                'is_system' => true,
            ],
            [
                'code' => '3300',
                'name' => 'Drawings',
                'type' => 'equity',
                'subtype' => 'owner_equity',
                'parent_code' => '3000',
                'normal_balance' => 'debit',
                'description' => 'Owner withdrawals from the business',
            ],
            [
                'code' => '3400',
                'name' => 'Dividends',
                'type' => 'equity',
                'subtype' => 'owner_equity',
                'parent_code' => '3000',
                'normal_balance' => 'debit',
                'description' => 'Dividends declared and paid',
            ],

            // =====================================================
            // INCOME (4000-4999)
            // =====================================================
            [
                'code' => '4000',
                'name' => 'Income',
                'type' => 'income',
                'subtype' => 'operating_income',
                'normal_balance' => 'credit',
                'description' => 'Income from business operations',
                'is_system' => true,
            ],
            [
                'code' => '4100',
                'name' => 'Sales Revenue',
                'type' => 'income',
                'subtype' => 'operating_income',
                'parent_code' => '4000',
                'normal_balance' => 'credit',
                'description' => 'Revenue from product sales',
                'is_system' => true,
            ],
            [
                'code' => '4110',
                'name' => 'Product Sales',
                'type' => 'income',
                'subtype' => 'operating_income',
                'parent_code' => '4100',
                'normal_balance' => 'credit',
                'description' => 'Revenue from selling products',
            ],
            [
                'code' => '4120',
                'name' => 'Sales Returns & Allowances',
                'type' => 'income',
                'subtype' => 'operating_income',
                'parent_code' => '4100',
                'normal_balance' => 'debit',
                'description' => 'Returns and allowances on sales (contra revenue)',
            ],
            [
                'code' => '4130',
                'name' => 'Sales Discounts',
                'type' => 'income',
                'subtype' => 'operating_income',
                'parent_code' => '4100',
                'normal_balance' => 'debit',
                'description' => 'Discounts given on sales (contra revenue)',
            ],
            [
                'code' => '4200',
                'name' => 'Service Revenue',
                'type' => 'income',
                'subtype' => 'operating_income',
                'parent_code' => '4000',
                'normal_balance' => 'credit',
                'description' => 'Revenue from services provided',
            ],
            [
                'code' => '4210',
                'name' => 'Consulting Revenue',
                'type' => 'income',
                'subtype' => 'operating_income',
                'parent_code' => '4200',
                'normal_balance' => 'credit',
                'description' => 'Revenue from consulting services',
            ],
            [
                'code' => '4220',
                'name' => 'Delivery Revenue',
                'type' => 'income',
                'subtype' => 'operating_income',
                'parent_code' => '4200',
                'normal_balance' => 'credit',
                'description' => 'Revenue from delivery services',
            ],
            [
                'code' => '4500',
                'name' => 'Other Income',
                'type' => 'income',
                'subtype' => 'other_income',
                'parent_code' => '4000',
                'normal_balance' => 'credit',
                'description' => 'Non-operating income',
            ],
            [
                'code' => '4510',
                'name' => 'Interest Income',
                'type' => 'income',
                'subtype' => 'other_income',
                'parent_code' => '4500',
                'normal_balance' => 'credit',
                'description' => 'Interest earned on bank balances',
            ],
            [
                'code' => '4520',
                'name' => 'Rental Income',
                'type' => 'income',
                'subtype' => 'other_income',
                'parent_code' => '4500',
                'normal_balance' => 'credit',
                'description' => 'Income from property rentals',
            ],
            [
                'code' => '4530',
                'name' => 'Gain on Asset Sale',
                'type' => 'income',
                'subtype' => 'other_income',
                'parent_code' => '4500',
                'normal_balance' => 'credit',
                'description' => 'Profit from selling fixed assets',
            ],
            [
                'code' => '4540',
                'name' => 'Foreign Exchange Gain',
                'type' => 'income',
                'subtype' => 'other_income',
                'parent_code' => '4500',
                'normal_balance' => 'credit',
                'description' => 'Gains from currency fluctuations',
            ],

            // =====================================================
            // EXPENSES (5000-5999)
            // =====================================================
            
            // Cost of Goods Sold (5000-5199)
            [
                'code' => '5000',
                'name' => 'Cost of Goods Sold',
                'type' => 'expense',
                'subtype' => 'cost_of_goods_sold',
                'normal_balance' => 'debit',
                'description' => 'Direct costs of products sold',
                'is_system' => true,
            ],
            [
                'code' => '5010',
                'name' => 'Purchases',
                'type' => 'expense',
                'subtype' => 'cost_of_goods_sold',
                'parent_code' => '5000',
                'normal_balance' => 'debit',
                'description' => 'Cost of inventory purchased',
            ],
            [
                'code' => '5020',
                'name' => 'Purchase Returns & Allowances',
                'type' => 'expense',
                'subtype' => 'cost_of_goods_sold',
                'parent_code' => '5000',
                'normal_balance' => 'credit',
                'description' => 'Returns and allowances on purchases',
            ],
            [
                'code' => '5030',
                'name' => 'Purchase Discounts',
                'type' => 'expense',
                'subtype' => 'cost_of_goods_sold',
                'parent_code' => '5000',
                'normal_balance' => 'credit',
                'description' => 'Discounts received on purchases',
            ],
            [
                'code' => '5040',
                'name' => 'Freight In',
                'type' => 'expense',
                'subtype' => 'cost_of_goods_sold',
                'parent_code' => '5000',
                'normal_balance' => 'debit',
                'description' => 'Shipping costs for inventory',
            ],
            [
                'code' => '5050',
                'name' => 'Direct Labor',
                'type' => 'expense',
                'subtype' => 'cost_of_goods_sold',
                'parent_code' => '5000',
                'normal_balance' => 'debit',
                'description' => 'Labor directly involved in production',
            ],

            // Operating Expenses (5200-5899)
            [
                'code' => '5200',
                'name' => 'Operating Expenses',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'normal_balance' => 'debit',
                'description' => 'Day-to-day business expenses',
                'is_system' => true,
            ],
            [
                'code' => '5210',
                'name' => 'Salaries & Wages',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Employee compensation',
            ],
            [
                'code' => '5211',
                'name' => 'Management Salaries',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5210',
                'normal_balance' => 'debit',
                'description' => 'Salaries for management staff',
            ],
            [
                'code' => '5212',
                'name' => 'Staff Salaries',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5210',
                'normal_balance' => 'debit',
                'description' => 'Salaries for regular staff',
            ],
            [
                'code' => '5213',
                'name' => 'Casual Wages',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5210',
                'normal_balance' => 'debit',
                'description' => 'Wages for casual workers',
            ],
            [
                'code' => '5220',
                'name' => 'Employee Benefits',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Benefits provided to employees',
            ],
            [
                'code' => '5221',
                'name' => 'NSSF Employer Contribution',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5220',
                'normal_balance' => 'debit',
                'description' => 'Employer NSSF contributions',
            ],
            [
                'code' => '5222',
                'name' => 'NHIF Employer Contribution',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5220',
                'normal_balance' => 'debit',
                'description' => 'Employer NHIF contributions',
            ],
            [
                'code' => '5223',
                'name' => 'Medical Insurance',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5220',
                'normal_balance' => 'debit',
                'description' => 'Staff medical insurance',
            ],
            [
                'code' => '5230',
                'name' => 'Rent Expense',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Office and warehouse rent',
            ],
            [
                'code' => '5240',
                'name' => 'Utilities',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Utility expenses',
            ],
            [
                'code' => '5241',
                'name' => 'Electricity',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5240',
                'normal_balance' => 'debit',
                'description' => 'Electricity bills',
            ],
            [
                'code' => '5242',
                'name' => 'Water',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5240',
                'normal_balance' => 'debit',
                'description' => 'Water bills',
            ],
            [
                'code' => '5243',
                'name' => 'Internet & Telephone',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5240',
                'normal_balance' => 'debit',
                'description' => 'Communication expenses',
            ],
            [
                'code' => '5250',
                'name' => 'Office Supplies',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Stationery and office supplies',
            ],
            [
                'code' => '5260',
                'name' => 'Marketing & Advertising',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Marketing and promotional expenses',
            ],
            [
                'code' => '5270',
                'name' => 'Transportation & Delivery',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Transport and delivery costs',
            ],
            [
                'code' => '5271',
                'name' => 'Fuel & Oil',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5270',
                'normal_balance' => 'debit',
                'description' => 'Vehicle fuel expenses',
            ],
            [
                'code' => '5272',
                'name' => 'Vehicle Maintenance',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5270',
                'normal_balance' => 'debit',
                'description' => 'Vehicle repairs and maintenance',
            ],
            [
                'code' => '5280',
                'name' => 'Insurance Expense',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Business insurance premiums',
            ],
            [
                'code' => '5290',
                'name' => 'Professional Fees',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Legal, accounting, and consulting fees',
            ],
            [
                'code' => '5291',
                'name' => 'Legal Fees',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5290',
                'normal_balance' => 'debit',
                'description' => 'Legal and compliance fees',
            ],
            [
                'code' => '5292',
                'name' => 'Accounting Fees',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5290',
                'normal_balance' => 'debit',
                'description' => 'Audit and accounting fees',
            ],
            [
                'code' => '5300',
                'name' => 'Bank Charges',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Bank fees and charges',
            ],
            [
                'code' => '5310',
                'name' => 'Depreciation Expense',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Depreciation on fixed assets',
                'is_system' => true,
            ],
            [
                'code' => '5320',
                'name' => 'Repairs & Maintenance',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'General repairs and maintenance',
            ],
            [
                'code' => '5330',
                'name' => 'License & Permits',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Business licenses and permits',
            ],
            [
                'code' => '5340',
                'name' => 'Bad Debt Expense',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Write-off of uncollectible accounts',
            ],
            [
                'code' => '5350',
                'name' => 'Meals & Entertainment',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Business meals and entertainment',
            ],
            [
                'code' => '5360',
                'name' => 'Travel Expenses',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Business travel costs',
            ],
            [
                'code' => '5370',
                'name' => 'Training & Development',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Staff training expenses',
            ],
            [
                'code' => '5380',
                'name' => 'Security Services',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Security guard and alarm services',
            ],
            [
                'code' => '5390',
                'name' => 'Cleaning Services',
                'type' => 'expense',
                'subtype' => 'operating_expense',
                'parent_code' => '5200',
                'normal_balance' => 'debit',
                'description' => 'Office cleaning services',
            ],

            // Other Expenses (5900-5999)
            [
                'code' => '5900',
                'name' => 'Other Expenses',
                'type' => 'expense',
                'subtype' => 'other_expense',
                'normal_balance' => 'debit',
                'description' => 'Non-operating expenses',
            ],
            [
                'code' => '5910',
                'name' => 'Interest Expense',
                'type' => 'expense',
                'subtype' => 'other_expense',
                'parent_code' => '5900',
                'normal_balance' => 'debit',
                'description' => 'Interest paid on loans',
            ],
            [
                'code' => '5920',
                'name' => 'Loss on Asset Sale',
                'type' => 'expense',
                'subtype' => 'other_expense',
                'parent_code' => '5900',
                'normal_balance' => 'debit',
                'description' => 'Loss from selling fixed assets',
            ],
            [
                'code' => '5930',
                'name' => 'Foreign Exchange Loss',
                'type' => 'expense',
                'subtype' => 'other_expense',
                'parent_code' => '5900',
                'normal_balance' => 'debit',
                'description' => 'Losses from currency fluctuations',
            ],
            [
                'code' => '5940',
                'name' => 'Penalties & Fines',
                'type' => 'expense',
                'subtype' => 'other_expense',
                'parent_code' => '5900',
                'normal_balance' => 'debit',
                'description' => 'Penalties and fines paid',
            ],
            [
                'code' => '5950',
                'name' => 'Donations & Contributions',
                'type' => 'expense',
                'subtype' => 'other_expense',
                'parent_code' => '5900',
                'normal_balance' => 'debit',
                'description' => 'Charitable donations',
            ],
        ];
    }
}
